# ------ Development ------

services:
  # Client service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    
    networks:
      - app_network
    
    depends_on:
      - backend
    
  # Server service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    networks:
      - app_network
    
    depends_on:
      - database

  # Database service
  database:
    image: mongo:latest
    ports:
      - "27017:27017"

    volumes:
      - db_store:/data/db

    networks:
      - app_network

# Volume
volumes:
  db_store:
    driver: local #persist mongodb data locally

# Network
networks:
  app_network:
    driver: bridge