# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [client]
        node-version: [22.x]

    steps:
      # download source code to github runner
    - uses: actions/checkout@v4

      # install nodejs in CI environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.service }}/package-lock.json

    - name: Install dependencies
      working-directory: ./${{ matrix.service }}
      run: npm install

    - name: Build frontend
      working-directory: ./${{ matrix.service }}
      run: npm run build

    - name: Run component tests
      working-directory: ./${{ matrix.service }}
      run: npm test --tests

    - name: Build Docker image
      run: docker build -t accommate-frontend ./${{ matrix.service }}

  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./${{ matrix.service }}
        run: npm install

      - name: Build backend
        working-directory: ./${{ matrix.service }}
        run: npm start

      - name: Build Docker image
        run: docker build -t accommate-backend ./${{ matrix.service }}
